[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ppd_xgboost"
version = "1.0.0"
description = "Federated Learning on PPD Dataset using XGBoost"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.13.0",
    "xgboost==2.0.3",
    "scikit-learn",
    "pandas",
    "numpy",
    "matplotlib",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "learner"

[tool.flwr.app.components]
serverapp = "pytorchexample.server_app:app"
clientapp = "pytorchexample.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 5
num-supernodes = 4          
learning-rate = 0.055

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 4

[tool.flwr.federations.local-simulation-gpu]
options.num-supernodes = 8
options.backend.client-resources.num-cpus = 2 # each ClientApp assumes to use 2CPUs
options.backend.client-resources.num-gpus = 0.0 # at most 5 ClientApp will run in a given GPU

[tool.flwr.federations.supergrid-deployment]
address = "supergrid.flower.ai"
enable-account-auth = true